name: Example Workflow  # Optional workflow name

on:                    # Trigger events
  push:
    branches:
      - main

jobs:                  # Define jobs
  build:               # Job name
    runs-on: ubuntu-latest  # Runner environment

    steps:             # Define steps
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a script
      run: echo "Hello, GitHub Actions!"
