name: Build and Publish Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version
    
    - name: Login to Docker Hub
      run: echo "${{ shahzaib783 }}" | docker login -u "${{ shahzaib783 }}" --password-stdin
    
    - name: Build Docker image
      run: docker build -t ${{ shahzaib783 }}/static-site .
    
    - name: Push Docker image
      run: docker push ${{ shahzaib783 }}/static-site
